name: Build

on:
  workflow_dispatch
    
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        repository: cheat-engine/cheat-engine
        ref: '7.4'
        
    - uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: "2.0.10"
        
    - run:  lazbuild -B "Cheat Engine/cheatengine.lpi" --cpu=x86_64 --build-mode="Release 64-Bit O4 AVX2"
    
    - uses: microsoft/setup-msbuild@v1.0.2

    - run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    
    - uses: actions/upload-artifact@main
      with:
        name: ${{ github.job }}
        path: Cheat Engine\bin
