name: DBVMbuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: cheat-engine/cheat-engine
          ref: '7.4'
          
      - run: sudo apt-get install -y yasm nasm mkisofs rar
      
      - name: Run a one-line script
        run: cd dbvm && make release

      - uses: actions/upload-artifact@main
        with:
          name: ${{ github.job }}
          path: dbvm/release
